@baseUrl= http://localhost:3000

###
GET  {{baseUrl}}/health
Content-Type: application/json

###
POST {{baseUrl}}/userClient
Content-Type: application/json

{
    "fullName": "Usuario Teste 10",
    "email": "usuario10@email.com",
    "password": "1234",
    "cpf": "12345678999"
}

###
GET {{baseUrl}}/userClient?page=1&limit=10
Content-Type: application/json

###
GET {{baseUrl}}/userClient/223c20ea-32d5-4d00-8da2-2530b73a49c5
Content-Type: application/json