@baseUrl= http://localhost:3000
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0OTdiMGU2My0wNTBiLTQxMTQtOTc0YS1kYjQ5Mzc2MDRhZmEiLCJlbWFpbCI6Im5vdm9AZW1haWwuY29tIiwiaWF0IjoxNzY2MTA3MzAzLCJleHAiOjE3NjYxMDc5MDN9.fSD5eMTOOaU30yHfkvF0kODSVz2lY4Lup7mx1p9fxrw

###
GET  {{baseUrl}}/health
Content-Type: application/json

###
POST {{baseUrl}}/userClient
Content-Type: application/json

{
    "fullName": "Novo Cliente Cadastrado",
    "email": "novo@email.com",
    "password": "1234",
    "cpf": "12345678910"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "novo@email.com",
    "password": "1234"
}

###
GET {{baseUrl}}/userClient?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/userClient/497b0e63-050b-4114-974a-db4937604afa
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
DELETE {{baseUrl}}/userClient/42d36331-6ded-4b75-a1aa-0038ee5335cb
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
PATCH {{baseUrl}}/userClient/223c20ea-32d5-4d00-8da2-2530b73a49c5
Content-Type: application/json

{
    "fullName": "Da Silva",
    "email": "da.silva.atualizado@email.com",
    "password": "1234"
}

###
POST {{baseUrl}}/deposit
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "amount": 100
}

###
POST {{baseUrl}}/withdraw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "amount": 100
}

###
POST {{baseUrl}}/transfer
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "toUserId": "497b0e63-050b-4114-974a-db4937604afa",
    "amount": 50
}

###
GET {{baseUrl}}/extract
Content-Type: application/json
Authorization: Bearer {{accessToken}}
