@baseUrl= http://localhost:3000
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYTU1N2I1My04NjdhLTQ1NDEtYTQ5My0xZjFkZGJkY2I5MTMiLCJlbWFpbCI6InVzdWFyaW8xMEBlbWFpbC5jb20iLCJpYXQiOjE3NjYwMTYyNzIsImV4cCI6MTc2NjAxNjg3Mn0.MlmKVAFsiR82Sc0YsWyiTyliNJEclPKpEXFLD-3m5ik

###
GET  {{baseUrl}}/health
Content-Type: application/json

###
POST {{baseUrl}}/userClient
Content-Type: application/json

{
    "fullName": "Usuario Teste 10",
    "email": "usuario10@email.com",
    "password": "1234",
    "cpf": "12345678999"
}

###
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "usuario10@email.com",
    "password": "1234"
}

###
GET {{baseUrl}}/userClient?page=1&limit=10
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
GET {{baseUrl}}/userClient/da557b53-867a-4541-a493-1f1ddbdcb913
Content-Type: application/json
Authorization: Bearer {{accessToken}}

###
DELETE {{baseUrl}}/userClient/5bfd7066-b2db-48f9-ac56-d8a1edd61b40

###
PATCH {{baseUrl}}/userClient/223c20ea-32d5-4d00-8da2-2530b73a49c5
Content-Type: application/json

{
    "fullName": "Da Silva",
    "email": "da.silva.atualizado@email.com",
    "password": "1234"
}

###
POST {{baseUrl}}/deposit
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "amount": 100
}

###
POST {{baseUrl}}/withdraw
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "amount": 100
}

###
POST {{baseUrl}}/transfer
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "toUserId": "7c8fd09d-a434-4ec9-bf56-d2386959d601",
    "amount": 100
}   